### ISSUE TITLE
Missing "left.png" & "right.png"

### ISSUE THREAD

**Issue by damonbauer** [sparkbox/mediaQueryBookmarklet#2]
The images:
"http://sparkbox.github.com/mediaQueryBookmarklet/images/left.png" & "http://sparkbox.github.com/mediaQueryBookmarklet/images/right.png"

are missing from this version. I can't seem to find a copy of them from past versions to update. Any chance those could get added in to re-enable support for positioning?

**Comment by cromwellryan** [comment]
You found them @damonbauer?
